name = "FixedRNGs"
uuid = "aa9b60e7-6b1c-4c29-a6e5-e43521412437"
authors = ["Chad Scherrer <chad.scherrer@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
